project:
  type: website
  output-dir: docs

website:
  title: "Hyejung Lee"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About  
        href: main_about.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Presentations
        href: presentations.qmd
      - text: Leadership
        href: leadership.qmd
    right:
      - icon: github
        href: https://github.com/hyejung0
      - icon: linkedin
        href: https://www.linkedin.com/in/hyejung-lee-b2249819b/
      # - icon: mortarboard
      #   href: https://scholar.google.com/
      - icon: envelope
        href: mailto:hyejung.lee@utah.edu

format:
  html:
    theme: cosmo
    toc: false
    smooth-scroll: true
